Members: 
- Manuela 
- Lucresse
- Likhita
- Gil-Allen
- Regis
- Lionel

# Convolution matrix

In [1]:
import numpy as np

# Defining convolution function

function takes three arguments: 

- input_matrix
- kernel(convolution filter)
- stride(the step size for sliding the kernel over the input matrix)

In [2]:
def convolve2d(input_matrix, kernel, stride):
    kernel_height, kernel_width = kernel.shape
    input_height, input_width = input_matrix.shape
    #check if the kernel is larger than the input image
    output_height = (input_height - kernel_height) // stride[0] + 1
    output_width = (input_width - kernel_width) // stride[1] + 1
    
    output_matrix = np.zeros((output_height, output_width))

    #iterate through each row in the input_matrix where the kernel can be placed based on the specific stride
    for i in range(0, input_height - kernel_height + 1, stride[0]):
        for j in range(0, input_width - kernel_width + 1, stride[1]):
            output_matrix[i // stride[0], j // stride[1]] = np.sum(input_matrix[i:i+kernel_height, j:j+kernel_width] * kernel)

    return output_matrix


In [3]:
#define an example input matrix and two convolution filters, one of size 3x3 and the other of size 5x5.
# Example input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]])

# Example 3x3 filter
kernel_3x3 = np.array([[1, 0, -1],
                       [2, 0, -2],
                       [1, 0, -1]])

# Example 5x5 filter
kernel_5x5 = np.array([[1, 1, 1, 1, 1],
                       [1, 1, 1, 1, 1],
                       [1, 1, 1, 1, 1],
                       [1, 1, 1, 1, 1],
                       [1, 1, 1, 1, 1]])

In [4]:
# Perform convolution with stride 1x1
output_3x3_stride1 = convolve2d(input_matrix, kernel_3x3, stride=(1, 1))
output_5x5_stride1 = convolve2d(input_matrix, kernel_5x5, stride=(1, 1))


In [5]:
#printing the results of the convolution operations
print("Output of 3x3 filter with stride 1x1:")
print(output_3x3_stride1)
print("\nOutput of 5x5 filter with stride 1x1:")
print(output_5x5_stride1)

Output of 3x3 filter with stride 1x1:
[[-8. -8. -8.]
 [-8. -8. -8.]
 [-8. -8. -8.]]

Output of 5x5 filter with stride 1x1:
[[325.]]


In [6]:
# Perform convolution with stride 2x2
output_3x3_stride2 = convolve2d(input_matrix, kernel_3x3, stride=(2, 2))
output_5x5_stride2 = convolve2d(input_matrix, kernel_5x5, stride=(2, 2))


In [7]:
#printing the results of the convolution operations
print("\nOutput of 3x3 filter with stride 2x2:")
print(output_3x3_stride2)
print("\nOutput of 5x5 filter with stride 2x2:")
print(output_5x5_stride2)


Output of 3x3 filter with stride 2x2:
[[-8. -8.]
 [-8. -8.]]

Output of 5x5 filter with stride 2x2:
[[325.]]
